### ISSUE TITLE
Dead proxies

### ISSUE THREAD

**Issue by Sycodevi** [daglaroglou/Nitro-Generator-N-Checker#3]
The program keeps saying "Dead Proxy, fetching a new one..."

**Comment by ReflexTheLegend** [comment]
im working on that... im aware that this occures... on previous version it doesnt appear tho...

**Comment by ReflexTheLegend** [comment]
seems like if you run main.py:
> Linux `python3 main.py`
> Windows `py main.py`

instead of the compiled executables the problem doesn't persist, try it out and tell me!

**Comment by Sycodevi** [comment]
The problem persists with both, I'm guessing it's due to regional technicalities if it is working fine for you.

**Comment by ReflexTheLegend** [comment]
Tell me if you can visit these sites: 
- https://sslproxies.org/
- https://free-proxy-list.net/

also in line `106` try increasing the timeout time to something like 15 or more depending on your connection.
![image](https://user-images.githubusercontent.com/70488503/187632070-15930f9f-efdb-43fb-ae1a-28f1175d38ac.png)
Maybe it needs more time to verify the availability of the proxy.

**Comment by Sycodevi** [comment]
I can visit both sites just fine, I tried the fix you mentioned but that didn't work either.

**Comment by ReflexTheLegend** [comment]
well try v1.7 too, if problem persists try to pip uninstall and pip install all the imported modules (the ones that arent integrated with python)

**Comment by daglaroglou** [comment]
works now

**Comment by OmorOrNot** [comment]
Nope
